churchauth/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('', views.home,name="home"),
    path('home', views.home,name="home"),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update, name="update"),
    path('delete/<int:id>', views.destroy ),
    path('register/', views.register, name='register'),
    path('leader', views.leader, name='leader'),
    path('profile/', views.profile, name='profile'),
    path('login/', auth_view.LoginView.as_view(template_name='authentication/login.html'), name="login"),
    path('logout/', auth_view.LogoutView.as_view(template_name='authentication/logout.html'), name="logout"),
    
]

urlpatterns += staticfiles_urlpatterns()

registration/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('churchauth.urls')),
]

churchauth/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.
class LeadersModel(models.Model):
  id= models.CharField(max_length=20, primary_key=True)
  name=models.CharField(max_length =200)
  phone= PhoneNumberField(unique = True, null = False, blank = False) 
  email  = models.EmailField(max_length=70,blank=True,unique=True)
  description= models.TextField()
  class Meta:
    db_table = "LeadersModel"
  def __str__(self):
        return self.name

churchauth/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import LeadersModel


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class LeadersForm(forms.ModelForm):
    class Meta:
        # specify model to be used
        model = LeadersModel
 
        # specify fields to be used
        fields = "__all__"

churchauth/views.py
from http.client import HTTPResponse
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from . forms import UserRegisterForm, LeadersForm
from django.contrib.auth.decorators import login_required
import requests
from .models import LeadersModel
# Create your views here.


def home(request):
  leader= LeadersModel.objects.all()
  return render(request, "authentication/index.html",{'leader':leader})

def leader(request):
    if request.method == "POST":
        form = LeadersForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/home')
            except:
                pass
    else:
        form = LeadersForm()
    return render(request, 'authentication/leaders.html', {'form': form})
def register(request):
  if request.method== "POST":
    form = UserRegisterForm(request.POST)
    if form.is_valid():
      form.save()
      username = form.cleaned_data.get('username')
      messages.success(request, f'Hello {username}, You Have Been Succesfully Registered')
      return redirect ('home')
  else:
    form = UserRegisterForm()
  return render(request, "authentication/register.html",{'form':form})

def edit(request, id):
    leader= LeadersModel.objects.get(id=id)
    return render(request, 'authentication/edit.html', {'leader': leader})

def update(request, id):
    leader= LeadersModel.objects.get(id=id)
    form = LeadersForm(request.POST, instance = leader)
    if form.is_valid():
        form.save()
        return redirect("/home")
    return render(request, 'authentication/edit.html', {'leader': leader})


def destroy(request,id):
    leader= LeadersModel.objects.get(id=id)
    leader.delete()
    return redirect("/home")

@login_required()
def profile(request):
  response=requests.get('https://type.fit/api/quotes').json()
  
  return render(request, 'authentication/profile.html', {'response':response}) 

templates/authentication/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--Css Style -->
    <link rel="stylesheet" href="{% static 'static/css/main.css' %}" type="text/css">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!--Font Link-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&family=Open+Sans:wght@800&display=swap" rel="stylesheet">

  </head>
  <body id="bg" style="background-image: url( 'static/images/bg6.jpg' );" >
  {% load static %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="main-navbar">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'images/in-logo-1.svg' %}" alt="" ></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <h3>ACK St.MATHEW'S</h3>
            
            <form class="d-flex" id="authstyle">
              {% if user.is_authenticated %}
                <a href="{% url 'profile' %}" class="btn" style="color: white; background-color: #fd5e14;"type="submit" id="header-links"> Profile </a>
                <a href="{% url 'logout' %}" class="btn" style="color: white; background-color: #fd5e14;"type="submit" id="header-links"> Logout </a>
              {% else %}
                <a href="{% url 'register' %}" class="btn" style="color: white; background-color: #fd5e14;"type="submit" id="header-links"> Create Account </a>
                <a href="{% url 'login' %}" class="btn" style="color: white; background-color: #fd5e14; margin-left: 10px; "type="submit" id="header-links">Log In</a>
              {% endif %}
              </form>
          </div>
        </div>
    </nav>

      <div>
        <div class="container">
          {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{message.tags}}">{{message}}</div>
          {% endfor %}
        {% endif %}
        </div>
        {% block content %}
        {% endblock content %}
      </div>

      <!-- Optional JavaScript; choose one of the two! -->

      <!-- Option 1: Bootstrap Bundle with Popper -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

      <!-- Option 2: Separate Popper and Bootstrap JS -->
      <!--
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
      -->
  </body>
</html>

templates/authentication/edit.html
{% extends 'authentication/base.html' %}

{% block content %}
<div class="container">
  <h3>You Can Edit A Leaders Details</h3>
</div>
<form method="POST" class="post-form" action="/update/{{leader.id}}">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Update Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Leader Id:</label>
    <div class="col-sm-4">
        <input type="text" name="id" id="id_id" required maxlength="20" value="{{ leader.id }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Leader Name:</label>
    <div class="col-sm-4">
        <input type="text" name="name" id="id_name" required maxlength="100" value="{{ leader.name }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Leader Email:</label>
    <div class="col-sm-4">
        <input type="email" name="email" id="id_email" required maxlength="254" value="{{ leader.email }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Leader Contact:</label>
    <div class="col-sm-4">
        <input type="text" name="contact" id="id_contact" required maxlength="15" value="{{ leader.phone }}" />
    </div>
  </div>

  <div class="form-group row">
  <label class="col-sm-2 col-form-label">Leader Description:</label>
  <div class="col-sm-4">
      <input type="text"   value="{{ leader.description }}" />
  </div>
  </div>
 </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <a href="/home"style="color: white; background-color: #fd5e14;" class="btn btn-primary">Update</a>
    </div>
  </div>
    </div>
</form>
{% endblock content %}

templates/authentication/index.html
{% extends 'authentication/base.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/auth.css' %}">
    <div class="container">
            <div class="row g-0">
                <div class="col-sm-6 col-md-8" id="header-text">
                  <h1 id="header-h1">Welcome to ACK St.MATHEW'S JUJA </h1>
                  <p id="header-paragraph">Juja, along Thika Super Highway. Behind Rubis Petrol Station Juja, Central Province, Kenya 01001 <br> A place of worship, fellowship, evangelism, growth and service.</p>
                  <p style="font-style: italic;color:black ;"id="header-paragraph">Create an Account so that you can stay updated and get some awesome quotes. <br> <br> <strong style="font-size: larger;">Once Logged in check your profile to pay for church membership.</strong> </p>
                  <a class="btn" style="color: white; background-color: #fd5e14;"type="submit" href="https://www.facebook.com/stmatthewsjuja/" id="body-link-row">Discover More</a>
                </div>

                <div class="col-6 col-md-4" id="header-image"><img src="images/in-liquid-slide-2.svg " alt=""></div>
              </div>
              <hr>
    </div>
<div class="container" style="color: white; text-align: center;font-style: oblique;">
  <h3>Below Is A List Of The Church Leaders <br> For You To Contact In Case Of Any Questions:</h3>
</div>
<div class="container" style="color:white; font-style: italic;">
  <table class="table table-striped table-bordered table-sm" style="color:white;">
      <thead class="thead-dark"style="color:white;">
      <tr>
          <th>Leader ID</th>
          <th>Leader Name</th>
          <th>Leader Email</th>
          <th>Leader Contact</th>
          <th>Leader Description</th>
          <th>Actions</th>
      </tr>
      </thead>
      <tbody style="color:white;">
      {% for leader in leader %}
        <tr>
          <td>{{ leader.id }}</td>
          <td>{{ leader.name }}</td>
          <td>{{ leader.email }}</td>
          <td>{{ leader.phone }}</td>
          <td>{{ leader.description }}</td>
          <td>
              <a style="color: white; background-color: #fd5e14;"href="/edit/{{ leader.id }}"class="btn"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
              <a style="color: white; background-color: #fd5e14;" class="btn"href="/delete/{{ leader.id }}">Delete</a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
  </table>
    <br>
    <br>
    <center>
        <a href="/leader"style="color: white; background-color: #fd5e14;" class="btn btn-primary">Add New Record</a>
    </center>
</div>    
{% endblock content %}

templates/authentication/leaders.html
{% extends 'authentication/base.html' %}

{% block content %}
<div class="container">
  <h3>You Can Add A Leaders Details</h3>
</div>
<form method="POST" class="post-form" action="/leader">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Enter Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Leader Id:</label>
    <div class="col-sm-4">
      {{ form.id }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Leader Name:</label>
    <div class="col-sm-4">
      {{ form.name }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Leader Email:</label>
    <div class="col-sm-4">
      {{ form.email }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Leader Contact:</label>
    <div class="col-sm-4">
      {{ form.phone }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Leader Description:</label>
    <div class="col-sm-4">
      {{ form.description }}
    </div>
  </div>
</div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button style="color: white; background-color: #fd5e14;" type="submit" class="btn btn-primary">Submit</button>
    </div>
  </div>
    </div>
</form>
{% endblock content %}

templates/authentication/login.html
{% extends 'authentication/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <div class="container" style="margin-top: 30px;">
    <form action="" method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
          <legend class="border-bottom mb-4" style="color: white;">Sign In Now</legend>
          {{ form|crispy }}
      </fieldset>
      <div class="form-group" id="signup-button">
          <button class="btn ">Sign In</button>
      </div>
      <div class="form-group">
          <small class="text-muted ml-3" >Don't have an account yet? <a href="{% url 'register' %}">Sign Up Today</a></small>
      </div>
    </form>
    </div>
{% endblock %}</title>

templates/authentication/logout.html
{% extends 'authentication/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <div class="container">
        <h1>You have been Logged out</h1>
        <h5><a href="{% url 'login' %}">Login In Again</a></h5>
    </div>
{% endblock %}</title>

templates/authentication/profile.html
{% extends 'authentication/base.html' %}
{% load crispy_forms_tags %}

{%load static%}

{% block content %}
<div id="bg"style="background-image: url( 'static/images/bg1.jpg' );">
    <div class="container" style="font-style: oblique;">
        <h3>Name:{{user.username}}</h3>
        <h3>Email:{{user.email}}</h3>
    </div>
    <hr>
    
    <div class="container" id="paypal-button-container"style="font-style: oblique;">
        <h3>Pay For Church Membership Below:</h3>
    </div><hr>

    <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=AfZnewpk9E3X6kILYTyHxMPV-s7lFmQ5USzKn_3yCxRlt5XIuHSjSolCXKeX83MVyr-J-yUfapwAD-4l"></script>

    <script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '50 Ksh'
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(orderData) {
                    // Successful capture! For demo purposes:
                    console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                    var transaction = orderData.purchase_units[0].payments.captures[0];
                    alert('Transaction '+ transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');

                    // Replace the above to show a success message within this page, e.g.
                    // const element = document.getElementById('paypal-button-container');
                    // element.innerHTML = '';
                    // element.innerHTML = '<h3>Thank you for your payment!</h3>';
                    // Or go to another URL:  actions.redirect('thank_you.html');
                });
            }


        }).render('#paypal-button-container');
    </script>
    <div class="container-fluid"style="font-style: oblique; color:black;">
        <h3>Check Out Amazing Quotes To Lift Your Spirits:</h3>
        {% for i in response%}
        <div style="border: 15px; border-radius:5px;outline-style: inset;"> {{i.text}}:  By {{i.author}}</div> <br>  
         
        {%endfor%}
    </div>  
</div>    
{% endblock %}

templates/authentication/register.html
{% extends 'authentication/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <div class="container" style="margin-top: 30px;">
    <form action="" method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
          <legend class="border-bottom mb-4" style="color: white;">Join Now</legend>
          {{ form|crispy }}
      </fieldset>
      <div class="form-group" id="signup-button">
          <button class="btn ">Sign Up</button>
      </div>
      <div class="form-group">
          
      </div>
    </form>
    </div>
{% endblock %}